version: "3.9"
services:
  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-container
    ports:
      - "8501:8501"
    networks:
      - lstm_rede

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
      - lstm_rede

networks:
  lstm_rede:
    driver: bridge